<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\GuideCategory;
use App\Models\ServiceGuide;
use Illuminate\Database\Seeder;

final class ServiceGuideSeeder extends Seeder
{
    public function run(): void
    {
        $today = now()->toDateString();

        foreach ($this->guides() as $index => $guide) {
            ServiceGuide::updateOrCreate(
                ['title' => $guide['title']],
                [
                    ...$guide,
                    'effective_date' => $today,
                    'sort_order' => $index,
                    'is_active' => true,
                ],
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function guides(): array
    {
        return [
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'PhilSys',
                'title' => 'Register for the PhilSys National ID',
                'summary' => 'Get your Philippine national ID (PhilSys). It works as a valid ID for most government and private transactions.',
                'requirements' => [
                    'PSA birth certificate',
                    'One government-issued ID, or supporting documents if none',
                    'Mobile number or email for the appointment',
                ],
                'steps' => [
                    'Register online at register.philsys.gov.ph for a slot',
                    'Set an appointment at the nearest registration center',
                    'Go to the center for capture of photo, fingerprints, and iris scan',
                    'Receive your PhilSys Number (PSN), then wait for the physical ID delivery',
                ],
                'where_to_go' => 'PhilSys registration centers (selected malls, LGU sites, and Post Offices). Start at philsys.gov.ph.',
                'fees' => 'Free',
                'notes' => null,
                'source_url' => 'https://philsys.gov.ph',
            ],
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'SSS',
                'title' => 'Get an SSS number and UMID card',
                'summary' => 'Register as an SSS member to get your SS number, then apply for a UMID card. Needed for loans, benefits, and pension.',
                'requirements' => [
                    'PSA birth certificate',
                    'One valid government ID, or two secondary IDs',
                    'Accomplished SSS Form E-1 (personal record)',
                    'Active email address and mobile number for My.SSS',
                ],
                'steps' => [
                    'Register online at My.SSS to generate your SS number',
                    'Complete your member registration (Form E-1) online or at a branch',
                    'Book a UMID card appointment through the SSS website or branch',
                    'Go to the branch on your schedule for photo, fingerprint, and signature capture',
                    'Wait for the UMID card delivery or claim it at the branch',
                ],
                'where_to_go' => 'Any SSS branch. Start online at sss.gov.ph (My.SSS).',
                'fees' => 'SS number and first UMID card: free',
                'notes' => 'Bring the original and a photocopy of every document.',
                'source_url' => 'https://www.sss.gov.ph',
            ],
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'NBI',
                'title' => 'Get an NBI Clearance',
                'summary' => 'A nationwide clearance often required for jobs, travel, and other government transactions.',
                'requirements' => [
                    'Two valid government-issued IDs',
                    'Registered NBI Clearance online account',
                    'Clearance fee',
                ],
                'steps' => [
                    'Register and set an appointment at clearance.nbi.gov.ph',
                    'Pay the fee online or over-the-counter',
                    'Go to the NBI center on your schedule for photo and fingerprints',
                    'Claim the clearance, or wait for delivery',
                ],
                'where_to_go' => 'Any NBI Clearance center. Book first at clearance.nbi.gov.ph.',
                'fees' => 'Around PHP 130 plus a service fee.',
                'notes' => 'A "hit" (name match) may need an extra day for verification.',
                'source_url' => 'https://clearance.nbi.gov.ph',
            ],
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'PNP',
                'title' => 'Get a Police Clearance',
                'summary' => 'A local clearance from the Philippine National Police, often asked for employment or permits.',
                'requirements' => [
                    'One or two valid IDs',
                    'Barangay clearance (in some cities)',
                    'Clearance fee',
                ],
                'steps' => [
                    'Register at pnpclearance.ph and set an appointment',
                    'Pay the fee online or at the station',
                    'Go to the police station for biometrics and photo',
                    'Claim your police clearance',
                ],
                'where_to_go' => 'Your city or municipal police station. Book at pnpclearance.ph.',
                'fees' => 'Usually PHP 150 (varies per LGU).',
                'notes' => null,
                'source_url' => 'https://pnpclearance.ph',
            ],
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'PHLPost',
                'title' => 'Get a Postal ID',
                'summary' => 'A widely accepted valid ID issued by the Philippine Postal Corporation.',
                'requirements' => [
                    'Accomplished postal ID application form',
                    'Proof of identity (PSA birth certificate or valid ID)',
                    'Proof of address (barangay certificate or a recent utility bill)',
                ],
                'steps' => [
                    'Fill out the application form at any post office',
                    'Submit your documents and pay the fee',
                    'Have your photo and fingerprints captured',
                    'Wait for the ID delivery',
                ],
                'where_to_go' => 'Any Post Office branch.',
                'fees' => 'Around PHP 504 (regular delivery).',
                'notes' => null,
                'source_url' => 'https://www.phlpost.gov.ph',
            ],
            [
                'category' => GuideCategory::Id->value,
                'agency' => 'COMELEC',
                'title' => 'Register to vote (voter registration)',
                'summary' => 'Register with COMELEC so you can vote and use your voter record as a valid document.',
                'requirements' => [
                    'One valid government-issued ID',
                    'You are at least 18 years old',
                    'You are a resident of the city or municipality for at least 6 months',
                ],
                'steps' => [
                    'Go to your local COMELEC (Office of the Election Officer)',
                    'Fill out the application for registration',
                    'Submit biometrics: photo, fingerprints, and signature',
                    'Wait for approval by the Election Registration Board',
                ],
                'where_to_go' => 'Your city or municipal COMELEC office.',
                'fees' => 'Free',
                'notes' => 'Registration is only open during COMELEC-announced periods.',
                'source_url' => 'https://comelec.gov.ph',
            ],

            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'SSS',
                'title' => 'File an SSS benefit claim',
                'summary' => 'How to claim SSS benefits such as sickness, maternity, or unemployment once you are a member.',
                'requirements' => [
                    'Active SSS membership and SS number',
                    'My.SSS online account',
                    'Supporting documents for the specific benefit (medical records, birth certificate, etc.)',
                    'Bank or e-wallet account enrolled in the Disbursement Account Enrollment Module (DAEM)',
                ],
                'steps' => [
                    'Log in to your My.SSS account',
                    'Enroll a disbursement account (bank or e-wallet)',
                    'Choose the benefit and fill out the online application',
                    'Upload the required supporting documents',
                    'Track the claim status online until it is credited',
                ],
                'where_to_go' => 'Online via My.SSS, or any SSS branch for assistance.',
                'fees' => 'Free',
                'notes' => 'Deadlines apply per benefit type. File as early as possible.',
                'source_url' => 'https://www.sss.gov.ph',
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'PhilHealth',
                'title' => 'Register as a PhilHealth member',
                'summary' => 'Enroll in PhilHealth to get health insurance coverage for hospital and medical expenses.',
                'requirements' => [
                    'PSA birth certificate or any valid ID',
                    'Accomplished PhilHealth Member Registration Form (PMRF)',
                    'Proof of income or employment, if applicable',
                ],
                'steps' => [
                    'Create an account on the PhilHealth Member Portal',
                    'Fill out the PMRF online or at a Local Health Insurance Office',
                    'Submit and get your PhilHealth Identification Number (PIN)',
                    'Pay contributions if you are a direct or voluntary member',
                ],
                'where_to_go' => 'Any PhilHealth Local Health Insurance Office (LHIO), or online.',
                'fees' => 'Registration free; contributions depend on membership type.',
                'notes' => null,
                'source_url' => 'https://www.philhealth.gov.ph',
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'Pag-IBIG',
                'title' => 'Become a Pag-IBIG (HDMF) member',
                'summary' => 'Register with Pag-IBIG Fund for savings, housing loans, and short-term loans.',
                'requirements' => [
                    'Accomplished Membership Registration/Remittance Form (MRRF)',
                    'One valid ID',
                    'PSA birth certificate, if you have no ID yet',
                ],
                'steps' => [
                    'Register online through the Virtual Pag-IBIG portal',
                    'Get your Pag-IBIG MID (membership ID) number',
                    'Start your monthly savings or contributions',
                ],
                'where_to_go' => 'Any Pag-IBIG (HDMF) branch, or Virtual Pag-IBIG online.',
                'fees' => 'Registration free; minimum monthly contribution applies.',
                'notes' => null,
                'source_url' => 'https://www.pagibigfund.gov.ph',
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'OSCA / LGU',
                'title' => 'Get a Senior Citizen ID and benefits',
                'summary' => 'The Senior Citizen ID gives 20% discounts, VAT exemption, and other privileges for those 60 and above.',
                'requirements' => [
                    'Proof you are 60 years old or above (PSA birth certificate or valid ID)',
                    'One ID photo (as required by your LGU)',
                    'Proof of residency',
                ],
                'steps' => [
                    'Go to the OSCA (Office for Senior Citizens Affairs) in your city or municipal hall',
                    'Fill out the application form',
                    'Submit your documents and photo',
                    'Claim your Senior Citizen ID and purchase booklet',
                ],
                'where_to_go' => 'The OSCA office at your city or municipal hall.',
                'fees' => 'Free',
                'notes' => null,
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'LGU / NCDA',
                'title' => 'Get a PWD ID and benefits',
                'summary' => 'The Person with Disability (PWD) ID gives 20% discounts, VAT exemption, and other privileges.',
                'requirements' => [
                    'Accomplished PWD ID application form',
                    'Medical certificate or clinical abstract confirming the disability',
                    'Two ID photos',
                    'Valid ID or proof of residency',
                ],
                'steps' => [
                    'Get a medical certificate from a licensed doctor',
                    'Go to the PDAO (Persons with Disability Affairs Office) or City/Municipal Health Office',
                    'Submit the form, medical certificate, and photos',
                    'Claim your PWD ID and purchase booklet',
                ],
                'where_to_go' => 'The PDAO or Health Office at your city or municipal hall.',
                'fees' => 'Free',
                'notes' => null,
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'LGU / DSWD',
                'title' => 'Get a Solo Parent ID',
                'summary' => 'The Solo Parent ID gives discounts, leave benefits, and other support under the Solo Parents Welfare Act.',
                'requirements' => [
                    'Barangay certificate confirming you are a solo parent',
                    'Documents proving solo parenthood (e.g. death certificate of spouse, or other proof)',
                    'One valid ID and ID photos',
                ],
                'steps' => [
                    'Get a barangay certificate of solo parenthood',
                    'Go to the City or Municipal Social Welfare and Development Office (CSWDO/MSWDO)',
                    'Submit the requirements and get assessed',
                    'Claim your Solo Parent ID',
                ],
                'where_to_go' => 'The Social Welfare Office (CSWDO/MSWDO) at your LGU.',
                'fees' => 'Free',
                'notes' => null,
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Benefit->value,
                'agency' => 'DSWD',
                'title' => 'Apply for 4Ps (Pantawid Pamilya)',
                'summary' => 'The Pantawid Pamilyang Pilipino Program gives cash grants to qualified poor families for health and education.',
                'requirements' => [
                    'You belong to a poor household (based on the DSWD Listahanan/targeting)',
                    'Has children 0 to 18 years old, or a pregnant member',
                    'Valid ID and proof of residency',
                ],
                'steps' => [
                    'Coordinate with your barangay or the DSWD field office',
                    'Undergo the DSWD assessment and validation',
                    'If qualified, register and comply with the health and education conditions',
                    'Receive the cash grants through the assigned channel',
                ],
                'where_to_go' => 'Your barangay or the nearest DSWD field office.',
                'fees' => 'Free',
                'notes' => 'Selection is based on DSWD targeting. Being listed is not guaranteed.',
                'source_url' => 'https://pantawid.dswd.gov.ph',
            ],

            [
                'category' => GuideCategory::Document->value,
                'agency' => 'PSA',
                'title' => 'Request a PSA birth certificate',
                'summary' => 'Get an official copy of a birth certificate from the Philippine Statistics Authority.',
                'requirements' => [
                    'Full name and details of the person on the certificate',
                    'Purpose of the request',
                    'Valid ID of the requester',
                    'Payment for the copy and delivery',
                ],
                'steps' => [
                    'Order online at PSA Serbilis or PSAHelpline',
                    'Pay the fee online or over-the-counter',
                    'Wait for delivery, or claim it at a PSA outlet',
                ],
                'where_to_go' => 'PSA Serbilis outlets, or order online for delivery.',
                'fees' => 'Around PHP 155 to PHP 365 per copy (varies).',
                'notes' => null,
                'source_url' => 'https://psaserbilis.com.ph',
            ],
            [
                'category' => GuideCategory::Document->value,
                'agency' => 'PSA',
                'title' => 'Request a PSA marriage certificate',
                'summary' => 'Get an official copy of a marriage certificate from the PSA.',
                'requirements' => [
                    'Full names of the husband and wife',
                    'Date and place of marriage',
                    'Valid ID of the requester',
                    'Payment for the copy and delivery',
                ],
                'steps' => [
                    'Order online at PSA Serbilis or PSAHelpline',
                    'Pay the fee',
                    'Wait for delivery, or claim it at a PSA outlet',
                ],
                'where_to_go' => 'PSA Serbilis outlets, or order online for delivery.',
                'fees' => 'Around PHP 155 to PHP 365 per copy (varies).',
                'notes' => null,
                'source_url' => 'https://psaserbilis.com.ph',
            ],
            [
                'category' => GuideCategory::Document->value,
                'agency' => 'PSA',
                'title' => 'Request a CENOMAR (no marriage record)',
                'summary' => 'The Certificate of No Marriage Record (CENOMAR) proves a person has no existing marriage on file.',
                'requirements' => [
                    'Full name and birth details of the person',
                    "Parents' full names",
                    'Valid ID of the requester',
                    'Payment for the copy and delivery',
                ],
                'steps' => [
                    'Order online at PSA Serbilis or PSAHelpline',
                    'Pay the fee',
                    'Wait for delivery, or claim it at a PSA outlet',
                ],
                'where_to_go' => 'PSA Serbilis outlets, or order online for delivery.',
                'fees' => 'Around PHP 210 to PHP 465 per copy (varies).',
                'notes' => null,
                'source_url' => 'https://psaserbilis.com.ph',
            ],
            [
                'category' => GuideCategory::Document->value,
                'agency' => 'Barangay',
                'title' => 'Get a Barangay Clearance',
                'summary' => 'A basic clearance from your barangay, often required for jobs, permits, and other IDs.',
                'requirements' => [
                    'Valid ID showing your current address',
                    'Proof of residency, if asked',
                    'Clearance fee',
                ],
                'steps' => [
                    'Go to your barangay hall',
                    'Fill out the request form and state your purpose',
                    'Pay the fee and claim the clearance',
                ],
                'where_to_go' => 'Your barangay hall.',
                'fees' => 'Usually PHP 50 to PHP 100 (varies per barangay).',
                'notes' => null,
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Document->value,
                'agency' => 'LGU Treasurer',
                'title' => 'Get a Cedula (Community Tax Certificate)',
                'summary' => 'The Community Tax Certificate, commonly required when notarizing documents or transacting with government offices.',
                'requirements' => [
                    'Valid ID',
                    'Income or salary details for the computation',
                ],
                'steps' => [
                    "Go to the City or Municipal Treasurer's Office, or your barangay",
                    'Provide your details and income',
                    'Pay the community tax and receive your cedula',
                ],
                'where_to_go' => "City or Municipal Treasurer's Office, or your barangay.",
                'fees' => 'Minimum PHP 5 plus an income-based tax.',
                'notes' => null,
                'source_url' => null,
            ],

            [
                'category' => GuideCategory::Relief->value,
                'agency' => 'LGU / DSWD',
                'title' => 'Claim food or fuel relief in AyudaLock',
                'summary' => 'How to check if you are eligible and claim relief through this app.',
                'requirements' => [
                    'Registered AyudaLock citizen account',
                    'Your PhilSys ID linked, if required by your LGU',
                    'You are listed in the beneficiary or franchise list',
                ],
                'steps' => [
                    'Open the Home tab and check Your eligibility',
                    'Go to Claim and pick a nearby store or station with stock',
                    'Reserve your item to lock a voucher (QR plus a code)',
                    'Show the voucher at the store within the time limit to redeem',
                ],
                'where_to_go' => 'Accredited Kadiwa stores and gas stations shown in the Claim tab.',
                'fees' => 'Free for eligible beneficiaries.',
                'notes' => 'Eligibility is set by your LGU or DSWD. If you are not listed, coordinate with your barangay.',
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Relief->value,
                'agency' => 'DSWD',
                'title' => 'Apply for AICS calamity assistance',
                'summary' => 'The Assistance to Individuals in Crisis Situations (AICS) helps families hit by calamity, illness, or other crises.',
                'requirements' => [
                    'Valid ID',
                    'Barangay certificate of residency or of the incident',
                    'Supporting documents (medical, death, or damage proof, depending on the need)',
                ],
                'steps' => [
                    'Go to the DSWD field office or a satellite/LGU desk',
                    'Get assessed by a social worker',
                    'Submit your documents',
                    'Receive the approved assistance',
                ],
                'where_to_go' => 'The nearest DSWD field office or LGU social welfare desk.',
                'fees' => 'Free',
                'notes' => null,
                'source_url' => 'https://www.dswd.gov.ph',
            ],
            [
                'category' => GuideCategory::Relief->value,
                'agency' => 'LTFRB',
                'title' => 'Avail the LTFRB fuel subsidy',
                'summary' => 'How qualified public-transport drivers and operators can avail the fuel subsidy program.',
                'requirements' => [
                    'Valid and active LTFRB franchise',
                    'Vehicle plate number and franchise details',
                    "Valid driver's license and ID",
                ],
                'steps' => [
                    'Confirm your franchise is active with LTFRB',
                    'Register or verify for the fuel subsidy program',
                    'Claim the subsidy through the accredited channel or app',
                ],
                'where_to_go' => 'LTFRB regional offices, or accredited fuel stations.',
                'fees' => 'Free for qualified franchise holders.',
                'notes' => null,
                'source_url' => 'https://ltfrb.gov.ph',
            ],

            [
                'category' => GuideCategory::Tax->value,
                'agency' => 'BIR',
                'title' => 'Register for a TIN (Tax Identification Number)',
                'summary' => 'Every taxpayer needs a TIN. It is required for employment, business, and many transactions.',
                'requirements' => [
                    'PSA birth certificate or any valid ID',
                    'Accomplished BIR registration form (1902 for employees, 1901 for self-employed)',
                    'Supporting documents depending on your taxpayer type',
                ],
                'steps' => [
                    'Identify your taxpayer type (employee, self-employed, etc.)',
                    'Fill out the correct BIR form (or use the online registration)',
                    'Submit it to the BIR Revenue District Office (RDO) that covers you',
                    'Receive your TIN (never apply for more than one)',
                ],
                'where_to_go' => 'The BIR RDO covering your address or employer. Some types can register online.',
                'fees' => 'TIN issuance is free.',
                'notes' => 'Having more than one TIN is against the law.',
                'source_url' => 'https://www.bir.gov.ph',
            ],
            [
                'category' => GuideCategory::Tax->value,
                'agency' => 'BIR',
                'title' => 'File your Income Tax Return (ITR)',
                'summary' => 'How to file your annual income tax return with the BIR.',
                'requirements' => [
                    'Your TIN',
                    'BIR Form 2316 (from your employer) or your books/records if self-employed',
                    'Proof of other income and deductions, if any',
                ],
                'steps' => [
                    'Gather your income documents for the year',
                    'Fill out the correct ITR form (1700, 1701, or 1701A)',
                    'File through eBIRForms or eFPS, or at your RDO',
                    'Pay any tax due through an accredited channel, if applicable',
                ],
                'where_to_go' => 'Online via eBIRForms/eFPS, or your BIR RDO.',
                'fees' => 'Filing is free; you only pay any tax due.',
                'notes' => 'The annual deadline is generally April 15. File early to avoid penalties.',
                'source_url' => 'https://www.bir.gov.ph',
            ],

            [
                'category' => GuideCategory::Work->value,
                'agency' => 'General',
                'title' => 'Prepare your pre-employment requirements',
                'summary' => 'The usual documents Philippine employers ask for when you get hired.',
                'requirements' => [
                    'NBI or Police Clearance',
                    'SSS, PhilHealth, and Pag-IBIG numbers',
                    'TIN (Tax Identification Number)',
                    'PSA birth certificate and valid IDs',
                    'Recent ID photos and, often, a medical exam result',
                ],
                'steps' => [
                    'Secure your government IDs and numbers early (SSS, PhilHealth, Pag-IBIG, TIN)',
                    'Get your NBI or Police clearance',
                    'Prepare your PSA documents and ID photos',
                    'Complete the pre-employment medical exam when required',
                ],
                'where_to_go' => 'Each agency for its own document; see the specific guides here.',
                'fees' => 'Varies per document.',
                'notes' => null,
                'source_url' => null,
            ],
            [
                'category' => GuideCategory::Work->value,
                'agency' => 'DMW / OWWA',
                'title' => 'Get an OEC for working abroad',
                'summary' => 'The Overseas Employment Certificate (OEC) is required for OFWs leaving for work abroad.',
                'requirements' => [
                    'Valid passport and work visa or permit',
                    'Valid employment contract',
                    'OWWA membership',
                    'e-Registration account with the Department of Migrant Workers (DMW)',
                ],
                'steps' => [
                    'Create or update your DMW (formerly POEA) online account',
                    'Ensure your OWWA membership is active',
                    'Process your OEC online or at a Migrant Workers Office',
                    'Present the OEC at the airport before departure',
                ],
                'where_to_go' => 'Online via the DMW portal, or a Migrant Workers Office (MWO/POEA).',
                'fees' => 'OEC is generally free; OWWA membership has a fee.',
                'notes' => 'Balik-manggagawa OFWs may qualify for OEC exemption.',
                'source_url' => 'https://www.dmw.gov.ph',
            ],

            [
                'category' => GuideCategory::Business->value,
                'agency' => 'DTI',
                'title' => 'Register a business name with DTI',
                'summary' => 'Sole proprietors register their business name with the DTI before operating.',
                'requirements' => [
                    'Proposed business name (with backups)',
                    'Valid ID',
                    'You are at least 18 years old',
                ],
                'steps' => [
                    'Search and reserve your business name at the DTI BNRS portal',
                    'Choose your territorial scope (barangay, city, regional, or national)',
                    'Pay the registration fee online',
                    'Download your DTI Certificate of Business Name Registration',
                ],
                'where_to_go' => 'Online at bnrs.dti.gov.ph, or a DTI Negosyo Center.',
                'fees' => 'PHP 200 to PHP 2,000 depending on scope, plus a documentary stamp.',
                'notes' => null,
                'source_url' => 'https://bnrs.dti.gov.ph',
            ],
            [
                'category' => GuideCategory::Business->value,
                'agency' => 'LGU',
                'title' => "Get a Mayor's / Business Permit",
                'summary' => 'The business permit lets you legally operate a business in a city or municipality.',
                'requirements' => [
                    'DTI, SEC, or CDA registration',
                    'Barangay business clearance',
                    'Lease contract or proof of business address',
                    'Other clearances (fire, sanitary) as required by the LGU',
                ],
                'steps' => [
                    'Get your barangay business clearance',
                    'Fill out the unified business permit application at the city/municipal hall',
                    'Submit requirements and get assessed for fees',
                    'Pay the fees and claim your business permit',
                ],
                'where_to_go' => "The Business Permits and Licensing Office (BPLO) at your city or municipal hall.",
                'fees' => 'Varies by LGU and business size.',
                'notes' => 'Business permits are renewed every January.',
                'source_url' => null,
            ],

            [
                'category' => GuideCategory::Travel->value,
                'agency' => 'DFA',
                'title' => 'Apply for a Philippine passport',
                'summary' => 'Get or renew your Philippine passport for travel and as a primary valid ID.',
                'requirements' => [
                    'Confirmed online appointment',
                    'PSA birth certificate (new applicants)',
                    'One valid government-issued ID',
                    'Old passport (for renewals)',
                ],
                'steps' => [
                    'Book an appointment at passport.gov.ph',
                    'Pay the processing fee',
                    'Go to the DFA Consular Office on your schedule with your documents',
                    'Have your photo and biometrics captured, then wait for release or delivery',
                ],
                'where_to_go' => 'Any DFA Consular Office. Book first at passport.gov.ph.',
                'fees' => 'PHP 950 (regular) or PHP 1,200 (expedite), plus delivery.',
                'notes' => 'Appointment slots fill fast; book early.',
                'source_url' => 'https://www.passport.gov.ph',
            ],
            [
                'category' => GuideCategory::Travel->value,
                'agency' => 'LTO',
                'title' => "Get a driver's license (student to non-professional)",
                'summary' => 'How to get your first driver\'s license through the LTO, starting with a student permit.',
                'requirements' => [
                    'Valid ID and PSA birth certificate',
                    "Certificate from an LTO-accredited driving school (theoretical, then practical)",
                    'Medical certificate from an LTO-accredited clinic',
                ],
                'steps' => [
                    'Complete the theoretical driving course and get a Student Permit',
                    'Practice, then complete the practical driving course',
                    'Apply for a non-professional license at the LTO after the required holding period',
                    'Pass the written and practical exams, then pay and claim your license',
                ],
                'where_to_go' => 'Any LTO Licensing Center or district office.',
                'fees' => 'Around PHP 585 plus exam and course fees.',
                'notes' => null,
                'source_url' => 'https://lto.gov.ph',
            ],
            [
                'category' => GuideCategory::Travel->value,
                'agency' => 'LTO',
                'title' => 'Register or renew a vehicle with LTO',
                'summary' => 'Keep your motor vehicle registration current with the LTO.',
                'requirements' => [
                    'Original OR/CR (Official Receipt and Certificate of Registration)',
                    'Valid Certificate of Emission Compliance (CEC)',
                    'Compulsory Third-Party Liability (CTPL) insurance',
                    "Valid driver's license",
                ],
                'steps' => [
                    'Get your vehicle emission-tested and secure CTPL insurance',
                    'Go to the LTO office or an authorized renewal center',
                    'Submit the documents and have the vehicle inspected if required',
                    'Pay the fees and claim your new OR and sticker',
                ],
                'where_to_go' => 'Any LTO office or authorized motor vehicle renewal center.',
                'fees' => 'Varies by vehicle type and any penalties.',
                'notes' => 'Renew based on your plate number schedule to avoid penalties.',
                'source_url' => 'https://lto.gov.ph',
            ],
        ];
    }
}
