export const qk = {
  eligibility: ["eligibility"] as const,
  allocations: ["allocations"] as const,
  claimReminders: ["claim-reminders"] as const,
  locations: ["locations"] as const,
  prices: ["prices"] as const,
  guides: ["guides"] as const,
  notifications: ["notifications"] as const,
  impactMap: ["impact-map"] as const,
  hazards: ["hazards"] as const,
  weather: ["weather"] as const,
  stats: ["stats"] as const,
  heatmap: ["heatmap"] as const,
  voucherKey: ["voucher-key"] as const,
  energyGrid: ["energy-grid"] as const,
  interruptions: ["interruptions"] as const,
  outageMap: ["outage-map"] as const,
};
